package com.project.web_hand_made_TMDT.Model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "inventory")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Inventory {

    @Id
    @Column(name = "product_id")
    private Integer productId;

    @Column(name = "quantity_in")
    private Integer quantityIn;

    @Column(name = "quantity_out")
    private Integer quantityOut;

    @Column(name = "quantity_damaged")
    private Integer quantityDamaged;

    @Column(name = "quantity_returned")
    private Integer quantityReturned;

    /* CRITICAL: This column is generated by the DB.
       insertable = false and updatable = false tells Hibernate
       to ignore this field during SAVE or UPDATE operations.
    */
    @Column(name = "quantity", insertable = false, updatable = false)
    private Integer quantity;

    @Column(name = "updated_at", insertable = false, updatable = false)
    private LocalDateTime updatedAt;

    // Optional: If you want to link directly to the Product object
    @OneToOne
    @MapsId // Tells JPA that productId is both the PK and the FK
    @JoinColumn(name = "product_id")
    private Product product;
}
